URL_PATTERN = '(\(|\[)?(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|](\)|\])?'
SUBREDDIT_PATTERN = '(\(|\[)?r/[A-Za-z]*(\)|\])?'
USER_PATTERN = '(\(|\[)?u/[A-Za-z]*(\)|\])?'
N_PATTERN = '.*\n.*\n.*\n.*'
YAN_PATTERN = '[^\u4e00-\u9fa5a-zA-Z\d,\,.，。!！*%￥$？?]+'